name: Emulator Trigger

on:
  push:
    branches:
      - main  # Define the branch you want to trigger on

jobs:
  emulator:
    runs-on: ubuntu-latest  # Define the operating system you want to run the job on

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # This action checks out your repository's code

      - name: Set up JDK and Android SDK
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: '31'  # Pixel 7 corresponds to Android 12 (API level 31)
          script: 'system-images;android-31;google_apis;x86'  # Choose appropriate system image
          architecture: 'x86'
          profile: 'pixel'  # Use pixel profile for Pixel devices
          emulator-options: '-no-snapshot'  # Customize emulator options as needed
          licenses: 'android-sdk-license-5be876d5'
      
      - name: Start emulator
        run: emulator -avd pixel -no-snapshot -no-audio -no-boot-anim -no-window -gpu swiftshader_indirect

      # Add additional steps as needed, such as running tests on the emulator

